### ISSUE TITLE
Automating some aspects

### ISSUE THREAD

**Issue by jkrumbiegel** [MakieOrg/BeautifulMakie#7]
It looks like currently, the examples have to be run locally, and then the resulting files moved manually into place? I couldn't really find more logic than in the files in this folder https://github.com/lazarusA/BeautifulMakie/tree/main/_assets

Maybe we can think about ways in which this can be streamlined, and maybe just run when deploying.

One can automatically create md files during deployment, and then run optimization again to include them as well, they don't have to be added to the git repository itself. Or maybe you had some specific ideas already?

That would also help when generating thumbnails for the overview page (it takes long to load otherwise) etc.

**Comment by lazarusA** [comment]
- files moved manually into place?
- Kind of, they are being saved into _assets/scripts/output/ and one can run them all with the script `generate_results.jl`. 
The Manifest.toml and Project.toml file are not in the main folder, I had some issues with Franklin at the time of deploying, all the time was failing to build. Right now, I just activate an external env and then run all the scripts. 

Now, the problem will be when there are some packages conflicts. In that case one needs to creates a new env for that particular script in order to work. Yes, again I did that locally and run it locally and then build the site with Franklin before deployment. An example for this scenario is this example. 

https://github.com/lazarusA/BeautifulMakie/tree/main/_assets/scripts/penguinsDataSetWithChain

 I don't have a clear idea how to call each script, then build automatically the corresponding .md file and then add the thumbnails into the main page. (that would be my workflow). And on top of that one needs to manually link this files to the left menu of the site. 

- Yes, I was thinking about automatisations, that's why all scripts and outputs files have the same name. 
-- One can automatically create md files during deployment
- I don't know how to do that, at the moment my .md files are calling basically the same name (.png, .jl, .out), but the titles are more descriptive, we could drop that also just putting the name of the file.

- it takes long to load otherwise 
yes, I know. This is definitely something that needs to be taking care of. I was thinking about lazy loading to fix that and keep the high resolution of the images.

**Comment by lazarusA** [comment]
This was my first attempt. Is better to have something (regarding the set of examples), than discussing endless hours about the best approach to automatised the whole thing. Now, it works, more or less. Probably, there are better ways to do it and we can do something about it, at least now we have something to work with.

**Comment by jkrumbiegel** [comment]
Yeah for sure, it's already quite good :) Ok then I have a better idea of how it works.

I guess it would get kind of crazy if every example had its own manifest, because then the amount of making new envs and recompiling when building would get out of hand. How about defining named environments, and new examples can either use existing environments, or they PR to add a new one. Then maybe one would have 5 to 10 environments maximum and it wouldn't take so long to build. Or at least use the same env for all examples that only use Makie and nothing external.

I would basically remove all md files and folders from the repo, then during deployment call a script like you're doing manually in the github actions yaml file. That would build the md's on the fly. Building locally will get more and more tedious for you, I think.
